### ISSUE TITLE
Todo 완료 목표일 & 버그 수정

### ISSUE THREAD

**Issue by chyeon97** [chyeon97/solarconnect-todo-list#3]
- [x]  UX구성 ( Datepicker)
- [x] 완료 목표일을 Todo 항목에서 볼 수 있게
- [x] 삭제 버그 수정
- [x] id 버그 수정
